defaults:
  - _self_
  - cameras:
      - video
  - read_images: opencv
  - visualization: default

  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

hydra:
  run:
    dir: logs
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.override_dirname}
