defaults:
  - _self_
  - cameras: video
  - read_images_to_batch: opencv
  - visualization: default

  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
  - override hydra/launcher: joblib

hydra:
  run:
    dir: logs
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.override_dirname}
