defaults:
  - _self_
  - cameras:
      - video
  - read_images: opencv
  - detector: yolov5
  - tracker: sort
  - visualization: default

hydra:
  run:
    dir: logs
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.override_dirname}
