name: pre-commit

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Check for files that changed in this push/pr
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "

      - name: Run pre-commit checks
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: --files ${{ steps.file_changes.outputs.files}}
